### ISSUE TITLE
Custom query suffix plugins trip up vite:import-analysis

### ISSUE THREAD

**Issue by haywirez** [tachibana-shin/vite-plugin-arraybuffer#2]
For some custom [query suffix import](https://vitejs.dev/guide/features.html#import-with-query-suffixes) plugins such as [vite-plugin-arraybuffer](https://github.com/tachibana-shin/vite-plugin-arraybuffer), `vite:import-analysis` stage gets tripped up which causes problems during testing with e.g. `vitest`.

```ts
import wasmBuffer from './test.wasm?arraybuffer'
```

```ts
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .wasm?arraybuffer file format, or if it's an asset, add "**/*.wasm?arraybuffer" to `assetsInclude` in your configuration.
```

I guess this is because only external URL, dataURI static imports are ignored by default.
Not sure if anything could be done on the plugin side, or we'd need to open a bug over at [vite](https://github.com/vitejs/vite/issues)?

**Comment by tachibana-shin** [comment]
Did version `vite-plugin-arraybuffer@0.0.4` fix your problem?

**Comment by haywirez** [comment]
Thank you for the updates, just tested `0.0.5` but the problem remains unfortunately. Could it be because other than JS files are only ignored during `?inline` or `?url`?

I was able to find a workaround to get the tests running by switching to dynamic imports: `import(/* @vite-ignore */ './file.wasm?arraybuffer' )`, even though it still throws the same import analysis error in the logs.

**Comment by tachibana-shin** [comment]
> Thank you for the updates, just tested `0.0.5` but the problem remains unfortunately. Could it be because other than JS files are only ignored during `?inline` or `?url`?
> 
> I was able to find a workaround to get the tests running by switching to dynamic imports: `import(/* @vite-ignore */ './file.wasm?arraybuffer' )`, even though it still throws the same import analysis error in the logs.

I developed this plugin on Vite 5 but didn't encounter any such problem. Can you create a minimal reproducible example for me?

**Comment by haywirez** [comment]
A bit closer to this mystery. It seems like the issue is only in-browser testing using `vitest`. 

Here's a simple example with no issues running tests in CLI mode, using `vite` + `vitest`:
[codesandbox.io/p/devbox/frosty-paper-f738ps](https://codesandbox.io/p/devbox/frosty-paper-f738ps
)

However, once you add the `@vitest/browser` package etc, it fails import-analysis:
[codesandbox.io/p/devbox/hopeful-oskar-rpdw7j](https://codesandbox.io/p/devbox/hopeful-oskar-rpdw7j
)

**Comment by haywirez** [comment]
All good — turns out the issue was with the vite plugin config [being overridden in browser tests](https://vitest.dev/config/file.html).

**Comment by tachibana-shin** [comment]
Good! Thanks for letting me know the problem has been resolved
