### ISSUE TITLE
version 0.0.4 fails with Remix

### ISSUE THREAD

**Issue by kevlened** [tachibana-shin/vite-plugin-arraybuffer#5]
Remix now uses Vite. When using this plugin in the Vite build, it fails with:

`Error: [vite:load-fallback] Could not load /react/jsx-runtime (imported by app/routes/test/route.tsx): ENOENT: no such file or directory, open '/react/jsx-runtime'`

This doesn't happen on version 0.0.2

**Comment by kevlened** [comment]
The autopilot doesn't offer a good solution. Ideally, this plugin is inert if it's not transforming a file. Returning `false` isn't inert in `resolveId`.

> Returning false signals that source should be treated as an external module and not included in the bundle
[source](https://rollupjs.org/plugin-development/#resolveid)

**Comment by tachibana-shin** [comment]
Does version 0.0.5 solve your problem?

**Comment by kevlened** [comment]
It does! Thanks
