### ISSUE TITLE
Sourcemap support

### ISSUE THREAD

**Issue by leo91000** [tachibana-shin/vite-plugin-arraybuffer#8]
**Is your feature request related to a problem? Please describe.**
When bundling with sourcemaps, we get this warning : `[plugin vite-plugin-arraybuffer] Sourcemap is likely to be incorrect: a plugin (vite-plugin-arraybuffer) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help`

**Describe the solution you'd like**
I would like for this warning to go away, it creates a lot of noise, specially if we have a lot of chunks.
As we don't need fancy sourcemaps, this is a possible solution : https://github.com/vanilla-extract-css/vanilla-extract/issues/699#issuecomment-1141765515 

**Describe alternatives you've considered**
I don't see any workaround

**Additional context**
I am willing to create a pull request if we agree on what need to be done

**Comment by tachibana-shin** [comment]
Fixed on version `0.07` thanks for support!

**Comment by leo91000** [comment]
Thank you !
